config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  root 'application#index'

  get 'lenders/:id/edit' => 'lenders#edit', as: 'lenders_edit'
  get 'lenders/:id/delete' => 'lenders#delete', as: 'lenders_delete'
  get 'lenders/' => 'lenders#show', as: 'lenders_show'
  get 'lenders_update/' => 'lenders#update', as: 'lenders_update'
  get 'lenders_new/' => 'lenders#new', as: 'lenders_new'
  get 'lenders_save/' => 'lenders#save', as: 'lenders_save'

  get 'borrowers/:id/edit' => 'borrowers#edit', as: 'borrowers_edit'
  get 'borrowers/:id/delete' => 'borrowers#delete', as: 'borrowers_delete'
  get 'borrowers/' => 'borrowers#show', as: 'borrowers_show'
  get 'borrowers_update/' => 'borrowers#update', as: 'borrowers_update'
  get 'borrowers_new/' => 'borrowers#new', as: 'borrowers_new'
  get 'borrowers_save/' => 'borrowers#save', as: 'borrowers_save'

  get 'active_borrowers/' => 'borrowers#active_borrowers', as: 'active_borrowers'
  get 'add_active/' => 'borrowers#add_active', as: 'add_active'
  get 'save_active/' => 'borrowers#save_active', as: 'save_active'
  get 'edit_active/:id/edit' => 'borrowers#edit_active', as: 'borrowers_edit_active'
  get 'save_edit_active/' => 'borrowers#save_edit_active', as: 'save_edit_active'
  get 'confirmed_applications/' => 'borrowers#confirmed_applications', as: 'confirmed_applications'
  get 'add_confirmed/' => 'borrowers#add_confirmed', as: 'add_confirmed'
  get 'save_confirmed/' => 'borrowers#save_confirmed', as: 'save_confirmed'
  get 'edit_confirmed/:id/edit' => 'borrowers#edit_confirmed', as: 'borrowers_edit_confirmed'
  get 'save_edit_confirmed/' => 'borrowers#save_edit_confirmed', as: 'save_edit_confirmed'
  get 'pending_applications/' => 'borrowers#pending_applications', as: 'pending_applications'
  get 'add_pending/' => 'borrowers#add_pending', as: 'add_pending'
  get 'save_pending/' => 'borrowers#save_pending', as: 'save_pending'
  get 'edit_pending/:id/edit' => 'borrowers#edit_pending', as: 'borrowers_edit_pending'
  get 'save_edit_pending/' => 'borrowers#save_edit_pending', as: 'save_edit_pending'

  get 'active_borrowers/:id/delete' => 'borrowers#active_delete', as: 'active_borrowers_delete'

  get 'admins/:id/edit' => 'admins#edit', as: 'admins_edit'
  get 'admins/:id/delete' => 'admins#delete', as: 'admins_delete'
  get 'admins/' => 'admins#show', as: 'admins_show'
  get 'admins_update/' => 'admins#update', as: 'admins_update'
  get 'admins_new/' => 'admins#new', as: 'admins_new'
  get 'admins_save/' => 'admins#save', as: 'admins_save'

  get 'tickets/:id/edit' => 'tickets#edit', as: 'tickets_edit'
  get 'tickets/:id/delete' => 'tickets#delete', as: 'tickets_delete'
  get 'tickets/' => 'tickets#show', as: 'tickets_show'
  get 'tickets_update/' => 'tickets#update', as: 'tickets_update'
  get 'tickets_new/' => 'tickets#new', as: 'tickets_new'

  get 'settings/' => 'settings#show', as: 'settings_show'
  post 'save_terms/' => 'settings#save_terms', as: 'settings_save_terms'
  post 'save_privacy/' => 'settings#save_privacy', as: 'settings_save_privacy'

  get '/ratings', to: 'admins#ratings'
  get '/chats', to: 'admins#chats'

end

app/controllers/borrowers_controller.rb
class BorrowersController < ApplicationController

  def show
    @borrowers = User.get_borrowers
  end

  def edit
    @borrower = User.find(params[:id])
  end

  def update
    User.find(params[:user][:id]).update_attributes(update_borrower_params params)

    redirect_to borrowers_show_url
  end

  def new
    @borrower = User.new
  end

  def delete
    User.destroy(params[:id])

    redirect_to borrowers_show_url
  end

  def save
    User.create(save_borrower_params params)

    redirect_to borrowers_show_url
  end

  # Active borrowers section

  def active_borrowers
    @borrowers = LoanApplication.where('loan_application_status = 1')
  end

  def pending_applications
    @borrowers = LoanApplication.where('loan_application_status = 2')
  end

  def confirmed_applications
    @borrowers = LoanApplication.where('loan_application_status = 3')
  end

  # Delete active applications section

  def active_delete
    LoanApplication.destroy(params[:id])

    redirect_to root_path
  end

  # Adding and edition applications section

  def add_active
    @borrowers = User.get_borrowers
    @lenders = User.get_lenders
  end

  def save_active
    LoanApplication.add_active active_loan_params(params), active_loan_app_params(params)

    redirect_to active_borrowers_path
  end

  def edit_active
    @borrowers = User.get_borrowers
    @lenders = User.get_lenders
    @loan_app = LoanApplication.find(params[:id])
  end

  def save_edit_active
    LoanApplication.edit_active active_loan_params(params), active_loan_app_params(params), params[:loan_app][:id]

    redirect_to active_borrowers_path
  end

  def add_pending
  end

  def save_pending
    LoanApplication.add_active active_loan_params(params), pending_loan_app_params(params)

    redirect_to pending_applications_path
  end

  def edit_pending
    @loan_app = LoanApplication.find(params[:id])
  end

  def save_edit_pending
    LoanApplication.edit_active active_loan_params(params), pending_loan_app_params(params), params[:loan_app][:id]

    redirect_to pending_applications_path
  end

  def add_confirmed
  end

  def save_confirmed
    LoanApplication.add_active active_loan_params(params), pending_loan_app_params(params)

    redirect_to confirmed_applications_path
  end

  def edit_confirmed
    @loan_app = LoanApplication.find(params[:id])
  end

  def save_edit_confirmed
    LoanApplication.edit_active active_loan_params(params), pending_loan_app_params(params), params[:loan_app][:id]

    redirect_to confirmed_applications_path
  end

  private

  def update_borrower_params(params)
    params.require(:user).permit(:name, :email, :phone, :is_home_rented, :device_type,
                                 :biz_reg_no, :address, :no_of_loans, :nric,
                                 :password, :status, :is_bankrupt, :salary_per_month,
                                 :salary_per_month, :job, :is_home_rented)
  end

  def save_borrower_params(params)
    params.require(:user).permit(:name, :email, :phone, :nric, :job, :address,
                                 :device_type,:is_home_rented,
                                 :biz_reg_no, :no_of_loans,
                                 :salary_per_month, :status, :is_borrower)
  end

  def active_loan_params(params)
    params.require(:loan).permit(:borrower_id, :amount, :time)
  end

  def active_loan_app_params(params)
    params.require(:loan_app).permit(:lender_id, :loan_application_status)
  end

  def pending_loan_app_params(params)
    params.require(:loan_app).permit(:lender_id, :loan_application_status, :loan_id,
                                 :return_amount, :per, :over_times, :bidded_time)
  end

end

app/views/borrowers/active_borrowers.html.erb
<body>
<!--[if lt IE 9]>
<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
<%= render 'admin/navigation' %>
<div id="wrapper">
  <!-- #wrapper -->
  <%= render 'admin/sidebar' %>

  <!--Body content-->
  <div id="content" class="page-content clearfix">
    <div class="contentwrapper">
      <!--Content wrapper-->
      <div class="heading">
        <!--  .heading-->
        <h3>Active Borrower Applications</h3>
        <div class="resBtnSearch">
          <a href="#"><span class="s16 icomoon-icon-search-3"></span></a>
        </div>

        <ul class="breadcrumb">
          <li>You are here:</li>
          <li>
            <a href="#" class="tip" title="back to dashboard">
              <i class="s16 icomoon-icon-screen-2"></i>
            </a>
                                <span class="divider">
                <i class="s16 icomoon-icon-arrow-right-3"></i>
            </span>
          </li>
          <li class="active">Blank Page</li>
        </ul>
      </div>
      <!-- End  / heading-->
      <!-- Start .row -->
      <div class="row">
        <div class="col-lg-6 col-md-12 sortable-layout">
          <!-- col-md-12 start here -->
          <div class="panel panel-default chart">
            <div class="panel-heading">
              <h4 class="panel-title">
                <i class="s16 icomoon-icon-bars"></i>
                <span>Loan Valume Metrics</span>
              </h4>
            </div>
            <div class="panel-body">
              <div class="simple-chart" style="height: 230px; width:100%;">
              </div>
            </div>
          </div>
          <!-- End .panel -->

        </div>
        <!-- col-md-12 end here -->
        <div class="col-lg-6 col-md-12 sortable-layout">
          <!-- col-lg-6 start here -->
          <div class="panel panel-default chart">
            <div class="panel-heading">
              <h4 class="panel-title">
                <i class="s16 icomoon-icon-bars"></i>
                <span>Real time applications</span>
              </h4>
            </div>
            <div class="panel-body">
              <div class="auto-update-chart" style="height: 230px;width:100%;">
              </div>
            </div>
          </div>
          <!-- End .panel -->
        </div>
        <!-- col-lg-6 end here -->
      </div>
      <!-- End .row -->
      <div class="row">
        <div class="col-lg-12">
          <!-- col-lg-12 start here -->
          <div class="panel panel-default toggle panelMove panelClose panelRefresh">
            <!-- Start .panel -->
            <div class="panel-heading">
              <h4 class="panel-title">Borrower Applications</h4>

              <div class="table-top-add-tools-btn">
                <a href="<%= add_active_path %>" class="btn btn-info mr5" type="button"><i class="fa fa-pencil"></i> Add</a>
                <div class="btn-group dropdown mr5">
                  <button data-toggle="dropdown" class="btn btn-info dropdown-toggle" type="button" aria-expanded="false">
                    <i class="fa fa-gears"></i> Tools
                    <span class="caret"></span>
                  </button>
                  <ul role="menu" class="dropdown-menu animated fadeIn" style="margin-left: -49px;">

                    <li>
                      <a href="#"><i class="fa fa-trash-o"></i> Delete</a>
                    </li>


                  </ul>
                </div>
              </div>

            </div>
            <div class="panel-body cstm-table">
              <table id="tabletools" class="table table-striped table-bordered" cellspacing="0" width="100%">
                <thead>
                <tr>
                  <th class="sort-n"><div class="checkbox-custom">
                    <input class="check-all" type="checkbox" id="masterCheck" value="option1">
                    <label for="masterCheck"></label>
                  </div></th>
                  <th>S/N</th>
                  <th>Name</th>
                  <th>ID Number</th>
                  <th>Amount Needed</th>
                  <th>Date</th>
                  <th>Time</th>
                  <th>Lender Name</th>
                  <th>Actions</th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                  <th></th>
                  <th>S/N</th>
                  <th>Name</th>
                  <th>ID Number</th>
                  <th>Amount Needed</th>
                  <th>Date</th>
                  <th>Time</th>
                  <th>Lender Name</th>
                  <th>Actions</th>
                </tr>
                </tfoot>
                <tbody>
                <% @borrowers.each_with_index do |value, index| %>
                    <tr>
                      <td><div class="checkbox-custom">
                        <input id="check" class="check" type="checkbox" value="option<%= index %>">
                        <label for="check"></label>
                      </div></td>
                      <td><%= index %></td>
                      <td><%= value.loan.user.name %></td>
                      <td><%= value.id %></td>
                      <td><%= value.loan.amount %></td>
                      <td><%= value.loan.time %></td>
                      <td>05:00</td>
                      <td><%= value.user.name %></td>
                      <td>
                        <div class="table-btns">
                          <ul>
                            <!--<li><a href="javascript:void(0);" class="view-btn">View</a></li>-->
                            <li><a href="<%= borrowers_edit_active_path value.id %>" class="edt-btn">Edit</a></li>
                            <li><a href="<%= active_borrowers_delete_path value.id %>" class="dlt-btn">Delete</a></li>
                          </ul>
                        </div>
                      </td>
                    </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>
          <!-- End .panel -->
        </div>
        <!-- col-lg-12 end here -->
      </div>
      <!-- End .row -->
    </div>
    <!-- End contentwrapper -->
  </div>
  <!-- End #content -->
  <div id="footer" class="clearfix sidebar-page right-sidebar-page">
    <!-- Start #footer  -->
    <p class="pull-left">
      Copyrights &copy; 2015 <a href="javascript:void(0);" class="color-blue strong" target="_blank">Cashmi</a> by The Bam Method Limited. All rights reserved.
    </p>
    <p class="pull-right">
      <a href="#" class="mr5">Terms of use</a>
      |
      <a href="#" class="ml5 mr25">Privacy police</a>
    </p>
  </div>
  <!-- End #footer  -->
</div>
<!-- / #wrapper -->
<!-- Back to top -->
<div id="back-to-top"><a href="#">Back to Top</a>
</div>
</body>

app/views/borrowers/confirmed_applications.html.erb
<body>
<!--[if lt IE 9]>
<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade
    your browser</a> to improve your experience.</p>
<![endif]-->
<%= render 'admin/navigation' %>
<div id="wrapper">
  <!-- #wrapper -->
  <%= render 'admin/sidebar' %>

  <!--Body content-->
  <div id="content" class="page-content clearfix">
    <div class="contentwrapper">
      <!--Content wrapper-->
      <div class="heading">
        <!--  .heading-->
        <h3>Confirmed Borrower Applications</h3>

        <div class="resBtnSearch">
          <a href="#"><span class="s16 icomoon-icon-search-3"></span></a>
        </div>

        <ul class="breadcrumb">
          <li>You are here:</li>
          <li>
            <a href="#" class="tip" title="back to dashboard">
              <i class="s16 icomoon-icon-screen-2"></i>
            </a>
                                <span class="divider">
                <i class="s16 icomoon-icon-arrow-right-3"></i>
            </span>
          </li>
          <li class="active">Blank Page</li>
        </ul>
      </div>
      <!-- End  / heading-->


      <!-- Start .row -->
      <div class="row">
        <div class="col-lg-6 col-md-12">
          <!-- col-md-12 start here -->
          <div class="panel panel-default chart">
            <div class="panel-heading">
              <h4 class="panel-title">
                <i class="s16 icomoon-icon-bars"></i>
                <span>Loan Valume Metrics</span>
              </h4>
            </div>
            <div class="panel-body">
              <div class="simple-chart" style="height: 230px; width:100%;">
              </div>
            </div>
          </div>
          <!-- End .panel -->

        </div>
        <!-- col-md-12 end here -->
        <div class="col-lg-6 col-md-12">
          <!-- col-lg-6 start here -->
          <div class="panel panel-default chart">
            <div class="panel-heading">
              <h4 class="panel-title">
                <i class="s16 icomoon-icon-bars"></i>
                <span>Real time applications</span>
              </h4>
            </div>
            <div class="panel-body">
              <div class="auto-update-chart" style="height: 230px;width:100%;">
              </div>
            </div>
          </div>
          <!-- End .panel -->
        </div>
        <!-- col-lg-6 end here -->
      </div>
      <!-- End .row -->

      <div class="row">
        <div class="col-lg-12">
          <!-- col-lg-12 start here -->
          <div class="panel panel-default toggle panelMove panelClose panelRefresh">
            <!-- Start .panel -->
            <div class="panel-heading">
              <h4 class="panel-title">Borrower Applications</h4>

              <div class="table-top-add-tools-btn">
                <a class="btn btn-info mr5" href="<%= add_confirmed_path %>"><i class="fa fa-pencil"></i> Add</a>

                <div class="btn-group dropdown mr5">
                  <button data-toggle="dropdown" class="btn btn-info dropdown-toggle" type="button" aria-expanded="false">
                    <i class="fa fa-gears"></i> Tools
                    <span class="caret"></span>
                  </button>
                  <ul role="menu" class="dropdown-menu animated fadeIn" style="margin-left: -49px;">

                    <li>
                      <a href="#"><i class="fa fa-trash-o"></i> Delete</a>
                    </li>


                  </ul>
                </div>
              </div>

            </div>
            <div class="panel-body cstm-table valign">
              <table id="tabletools" class="table table-striped table-bordered" cellspacing="0" width="100%">
                <thead>
                <tr>
                  <th class="sort-n">
                    <div class="checkbox-custom">
                      <input class="check-all" type="checkbox" id="masterCheck" value="option1">
                      <label for="masterCheck"></label>
                    </div>
                  </th>
                  <th>S/N</th>
                  <th>Loan ID</th>
                  <th>Borrower ID</th>
                  <th>Borrower Name</th>
                  <th>Request Amount</th>
                  <th>Time</th>
                  <th>Lender ID</th>
                  <th>Lender Name</th>
                  <th>Return Amount</th>
                  <th>Per</th>
                  <th>Over Times</th>
                  <th>Bidded Time</th>
                  <th>Confirmed Time</th>
                  <th>EIR Rate</th>
                  <th>Actions</th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                  <th></th>
                  <th>S/N</th>
                  <th>Loan ID</th>
                  <th>Borrower ID</th>
                  <th>Borrower Name</th>
                  <th>Request Amount</th>
                  <th>Time</th>
                  <th>Lender ID</th>
                  <th>Lender Name</th>
                  <th>Return Amount</th>
                  <th>Per</th>
                  <th>Over Times</th>
                  <th>Bidded Time</th>
                  <th>Confirmed Time</th>
                  <th>EIR Rate</th>
                  <th>Actions</th>
                </tr>
                </tfoot>
                <tbody>
                <% @borrowers.each_with_index do |value, index| %>
                    <tr>
                      <td>
                        <div class="checkbox-custom">
                          <input id="check" class="check" type="checkbox" value="option<%= index %>">
                          <label for="check"></label>
                        </div>
                      </td>
                      <td><%= index %></td>
                      <td><%= value.loan_id %></td>
                      <td><%= value.loan.borrower_id %></td>
                      <td><%= value.loan.user.name %></td>
                      <td><%= value.loan.amount %></td>
                      <td><%= value.loan.time %></td>
                      <td><%= value.lender_id %></td>
                      <td><%= value.user.name %></td>
                      <td><%= value.return_amount %></td>
                      <td><%= value.per %></td>
                      <td><%= value.over_times %></td>
                      <td><%= value.bidded_time %></td>
                      <td><%= value.confirmed_time %></td>
                      <td>00</td>
                      <td>
                        <div class="table-btns">
                          <ul>
                            <li><a href="<%= borrowers_edit_confirmed_path value.id %>" class="edt-btn">Edit</a></li>
                            <li><a href="<%= active_borrowers_delete_path value.id %>" class="dlt-btn">Delete</a></li>
                          </ul>
                        </div>
                      </td>
                    </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>
          <!-- End .panel -->
        </div>
        <!-- col-lg-12 end here -->
      </div>
      <!-- End .row -->

    </div>
    <!-- End contentwrapper -->
  </div>
  <!-- End #content -->
  <div id="footer" class="clearfix sidebar-page">
    <!-- Start #footer  -->
    <p class="pull-left">
      Copyrights &copy; 2015 <a href="javascript:void(0);" class="color-blue strong" target="_blank">Cashmi</a> by The
      Bam Method Limited. All rights reserved.
    </p>

    <p class="pull-right">
      <a href="#" class="mr5">Terms of use</a>
      |
      <a href="#" class="ml5 mr25">Privacy police</a>
    </p>
  </div>
  <!-- End #footer  -->
</div>
<!-- / #wrapper -->
<!-- Back to top -->
<div id="back-to-top"><a href="#">Back to Top</a>
</div>


<!--Style 2 Fade in scale modal -->
<div class="modal fade modal-style2" id="modal-style2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title" id="mySmallModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        <object width="100%" height="200" type="application/pdf" data="Files/IPA.pdf">

        </object>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<!-- /.modal -->
<!--[if lt IE 9]>
<script type="text/javascript" src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
</body>

app/views/borrowers/pending_applications.html.erb
<body>
<!--[if lt IE 9]>
<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade
    your browser</a> to improve your experience.</p>
<![endif]-->
<%= render 'admin/navigation' %>
<div id="wrapper">
  <!-- #wrapper -->
  <%= render 'admin/sidebar' %>

  <!--Body content-->
  <div id="content" class="page-content clearfix">
    <div class="contentwrapper">
      <!--Content wrapper-->
      <div class="heading">
        <!--  .heading-->
        <h3>Pending Borrower Application</h3>

        <div class="resBtnSearch">
          <a href="#"><span class="s16 icomoon-icon-search-3"></span></a>
        </div>

        <ul class="breadcrumb">
          <li>You are here:</li>
          <li>
            <a href="#" class="tip" title="back to dashboard">
              <i class="s16 icomoon-icon-screen-2"></i>
            </a>
                                <span class="divider">
                <i class="s16 icomoon-icon-arrow-right-3"></i>
            </span>
          </li>
          <li class="active">Blank Page</li>
        </ul>
      </div>
      <!-- End  / heading-->
      <!-- Start .row -->
      <div class="row">
        <div class="col-lg-6 col-md-12 sortable-layout">
          <!-- col-md-12 start here -->
          <div class="panel panel-default chart">
            <div class="panel-heading">
              <h4 class="panel-title">
                <i class="s16 icomoon-icon-bars"></i>
                <span>Loan Valume Metrics</span>
              </h4>
            </div>
            <div class="panel-body">
              <div class="simple-chart" style="height: 230px; width:100%;">
              </div>
            </div>
          </div>
          <!-- End .panel -->

        </div>
        <!-- col-md-12 end here -->
        <div class="col-lg-6 col-md-12 sortable-layout">
          <!-- col-lg-6 start here -->
          <div class="panel panel-default chart">
            <div class="panel-heading">
              <h4 class="panel-title">
                <i class="s16 icomoon-icon-bars"></i>
                <span>Real time applications</span>
              </h4>
            </div>
            <div class="panel-body">
              <div class="auto-update-chart" style="height: 230px;width:100%;">
              </div>
            </div>
          </div>
          <!-- End .panel -->
        </div>
        <!-- col-lg-6 end here -->
      </div>
      <!-- End .row -->
      <div class="row">
        <div class="col-lg-12">
          <!-- col-lg-12 start here -->
          <div class="panel panel-default toggle panelMove panelClose panelRefresh">
            <!-- Start .panel -->
            <div class="panel-heading">
              <h4 class="panel-title">Borrower Applications</h4>

              <div class="table-top-add-tools-btn">
                <a class="btn btn-info mr5" href="<%= add_pending_path %>"><i class="fa fa-pencil"></i>
                  Add</a>

                <div class="btn-group dropdown mr5">
                  <button data-toggle="dropdown" class="btn btn-info dropdown-toggle" type="button" aria-expanded="false">
                    <i class="fa fa-gears"></i> Tools
                    <span class="caret"></span>
                  </button>
                  <ul role="menu" class="dropdown-menu animated fadeIn" style="margin-left: -49px;">

                    <li>
                      <a href="#"><i class="fa fa-trash-o"></i> Delete</a>
                    </li>


                  </ul>
                </div>
              </div>

            </div>
            <div class="panel-body cstm-table valign">
              <table id="tabletools" class="table table-striped table-bordered" cellspacing="0" width="100%">
                <thead>
                <tr>
                  <th class="sort-n">
                    <div class="checkbox-custom">
                      <input class="check-all" type="checkbox" id="masterCheck" value="option1">
                      <label for="masterCheck"></label>
                    </div>
                  </th>
                  <th>S/N</th>
                  <th>Loan ID</th>
                  <th>Borrower ID</th>
                  <th>Borrower Name</th>
                  <th>Request Amount</th>
                  <th>Date</th>
                  <th>Time</th>
                  <th>Lender ID</th>
                  <th>Lender Name</th>
                  <th>Return Amount</th>
                  <th>Per</th>
                  <th>Over Times</th>
                  <th>Bidded Time</th>
                  <th>EIR Rate</th>
                  <th>Actions</th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                  <th></th>
                  <th>S/N</th>
                  <th>Loan ID</th>
                  <th>Borrower ID</th>
                  <th>Borrower Name</th>
                  <th>Request Amount</th>
                  <th>Date</th>
                  <th>Time</th>
                  <th>Lender ID</th>
                  <th>Lender Name</th>
                  <th>Return Amount</th>
                  <th>Per</th>
                  <th>Over Times</th>
                  <th>Bidded Time</th>
                  <th>EIR Rate</th>
                  <th>Actions</th>
                </tr>
                </tfoot>
                <tbody>
                <% @borrowers.each_with_index do |value, index| %>
                    <tr>
                      <td>
                        <div class="checkbox-custom">
                          <input id="check" class="check" type="checkbox" value="option<%= index %>">
                          <label for="check"></label>
                        </div>
                      </td>
                      <td><%= index %></td>
                      <td><%= value.loan.id %></td>
                      <td><%= value.loan.borrower_id %></td>
                      <td><%= value.loan.user.name %></td>
                      <td><%= value.loan.amount %></td>
                      <td><%= value.loan.time %></td>
                      <td>05:00</td>
                      <td><%= value.lender_id %></td>
                      <td><%= value.user.name %></td>
                      <td><%= value.return_amount %></td>
                      <td><%= value.per %></td>
                      <td><%= value.over_times %></td>
                      <td><%= value.bidded_time %></td>
                      <td>00</td>
                      <td>
                        <div class="table-btns">
                          <ul>
                            <li><a href="<%= borrowers_edit_pending_path value.id %>" class="edt-btn">Edit</a></li>
                            <li><a href="<%= active_borrowers_delete_path value.id %>" class="dlt-btn">Delete</a></li>
                          </ul>
                        </div>
                      </td>
                    </tr>
                <% end %>

                </tbody>
              </table>
            </div>
          </div>
          <!-- End .panel -->
        </div>
        <!-- col-lg-12 end here -->
      </div>
      <!-- End .row -->
    </div>
    <!-- End contentwrapper -->
  </div>
  <!-- End #content -->
  <div id="footer" class="clearfix sidebar-page">
    <!-- Start #footer  -->
    <p class="pull-left">
      Copyrights &copy; 2015 <a href="javascript:void(0);" class="color-blue strong" target="_blank">Cashmi</a> by The
      Bam Method Limited. All rights reserved.
    </p>

    <p class="pull-right">
      <a href="#" class="mr5">Terms of use</a>
      |
      <a href="#" class="ml5 mr25">Privacy police</a>
    </p>
  </div>
  <!-- End #footer  -->
</div>
<!-- / #wrapper -->
<!-- Back to top -->
<div id="back-to-top"><a href="#">Back to Top</a>
</div>
<!--[if lt IE 9]>
<script type="text/javascript" src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
</body>