config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  root 'application#index'

  get 'lenders/:id/edit' => 'lenders#edit', as: 'lenders_edit'
  get 'lenders/:id/delete' => 'lenders#delete', as: 'lenders_delete'
  get 'lenders/' => 'lenders#show', as: 'lenders_show'
  get 'lenders_update/' => 'lenders#update', as: 'lenders_update'
  get 'lenders_new/' => 'lenders#new', as: 'lenders_new'
  get 'lenders_save/' => 'lenders#save', as: 'lenders_save'

  get 'borrowers/:id/edit' => 'borrowers#edit', as: 'borrowers_edit'
  get 'borrowers/:id/delete' => 'borrowers#delete', as: 'borrowers_delete'
  get 'borrowers/' => 'borrowers#show', as: 'borrowers_show'
  get 'borrowers_update/' => 'borrowers#update', as: 'borrowers_update'
  get 'borrowers_new/' => 'borrowers#new', as: 'borrowers_new'
  get 'borrowers_save/' => 'borrowers#save', as: 'borrowers_save'

  get 'active_borrowers/' => 'borrowers#active_borrowers', as: 'active_borrowers'
  get 'add_active/' => 'borrowers#add_active', as: 'add_active'
  get 'save_active/' => 'borrowers#save_active', as: 'save_active'
  get 'edit_active/:id/edit' => 'borrowers#edit_active', as: 'borrowers_edit_active'
  get 'save_edit_active/' => 'borrowers#save_edit_active', as: 'save_edit_active'
  get 'confirmed_applications/' => 'borrowers#confirmed_applications', as: 'confirmed_applications'
  get 'add_confirmed/' => 'borrowers#add_confirmed', as: 'add_confirmed'
  get 'save_confirmed/' => 'borrowers#save_confirmed', as: 'save_confirmed'
  get 'edit_confirmed/:id/edit' => 'borrowers#edit_confirmed', as: 'borrowers_edit_confirmed'
  get 'save_edit_confirmed/' => 'borrowers#save_edit_confirmed', as: 'save_edit_confirmed'
  get 'pending_applications/' => 'borrowers#pending_applications', as: 'pending_applications'
  get 'add_pending/' => 'borrowers#add_pending', as: 'add_pending'
  get 'save_pending/' => 'borrowers#save_pending', as: 'save_pending'
  get 'edit_pending/:id/edit' => 'borrowers#edit_pending', as: 'borrowers_edit_pending'
  get 'save_edit_pending/' => 'borrowers#save_edit_pending', as: 'save_edit_pending'

  get 'active_borrowers/:id/delete' => 'borrowers#active_delete', as: 'active_borrowers_delete'

  get 'admins/:id/edit' => 'admins#edit', as: 'admins_edit'
  get 'admins/:id/delete' => 'admins#delete', as: 'admins_delete'
  get 'admins/' => 'admins#show', as: 'admins_show'
  get 'admins_update/' => 'admins#update', as: 'admins_update'
  get 'admins_new/' => 'admins#new', as: 'admins_new'
  get 'admins_save/' => 'admins#save', as: 'admins_save'

  get 'tickets/:id/edit' => 'tickets#edit', as: 'tickets_edit'
  get 'tickets/:id/delete' => 'tickets#delete', as: 'tickets_delete'
  get 'tickets/' => 'tickets#show', as: 'tickets_show'
  get 'tickets_update/' => 'tickets#update', as: 'tickets_update'
  get 'tickets_new/' => 'tickets#new', as: 'tickets_new'

  get 'settings/' => 'settings#show', as: 'settings_show'
  post 'save_terms/' => 'settings#save_terms', as: 'settings_save_terms'
  post 'save_privacy/' => 'settings#save_privacy', as: 'settings_save_privacy'

  get '/ratings', to: 'admins#ratings'
  get '/chats', to: 'admins#chats'

end

app/views/admins/new.html.erb
<body>
<!--[if lt IE 9]>
<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade
    your browser</a> to improve your experience.</p>
<![endif]-->
<%= render 'admin/navigation' %>
<div id="wrapper">
  <!-- #wrapper -->
  <%= render 'admin/sidebar' %>

  <!--Body content-->
  <div id="content" class="page-content clearfix">
    <div class="contentwrapper">
      <!--Content wrapper-->
      <div class="heading">
        <!--  .heading-->
        <h3>Admin Applications form</h3>

        <div class="resBtnSearch">
          <a href="#"><span class="s16 icomoon-icon-search-3"></span></a>
        </div>

        <ul class="breadcrumb">
          <li>You are here:</li>
          <li>
            <a href="#" class="tip" title="back to dashboard">
              <i class="s16 icomoon-icon-screen-2"></i>
            </a>
                                <span class="divider">
                <i class="s16 icomoon-icon-arrow-right-3"></i>
            </span>
          </li>
          <li class="active">Blank Page</li>
        </ul>
      </div>
      <!-- End  / heading-->
      <!-- Start .row -->
      <div class="row">
        <div class="col-md-12 sortable-layout">
          <!-- col-md-6 start here -->
          <div class="panel panel-default toggle panelClose panelRefresh panelMove">
            <!-- Start .panel -->
            <div class="panel-heading">
              <h4 class="panel-title"><i class="s16 fa fa-edit"></i> Form</h4>
            </div>
            <div class="panel-body">
              <form class="form-horizontal" action="<%= admins_save_path %>">
                <!--<div class="form-group">-->
                  <!--<label for="" class="col-lg-2 col-md-3 control-label">User Name</label>-->

                  <!--<div class="col-lg-10 col-md-9">-->
                    <!--<input type="text" name="default" class="form-control">-->
                  <!--</div>-->
                <!--</div>-->

                <!--<div class="form-group">-->
                  <!--<label for="" class="col-lg-2 col-md-3 control-label">Name</label>-->

                  <!--<div class="col-lg-10 col-md-9">-->
                    <!--<input type="text" name="default" class="form-control">-->
                  <!--</div>-->
                <!--</div>-->

                <div class="form-group">
                  <label for="" class="col-lg-2 col-md-3 control-label">Email</label>

                  <div class="col-lg-10 col-md-9">
                    <input type="text" name="user[email]" class="form-control">
                  </div>
                </div>

                <div class="form-group">
                  <label for="" class="col-lg-2 col-md-3 control-label">Password</label>

                  <div class="col-lg-10 col-md-9">
                    <input type="password" name="user[password]" class="form-control">
                  </div>
                </div>


                <div class="view-chat-btm-btn">
                  <div class="btn-group">
                    <button class="btn btn-danger" type="submit">Submit</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
          <!-- End .panel -->


        </div>
        <!-- col-md-12 end here -->

      </div>
      <!-- End .row -->
    </div>
    <!-- End contentwrapper -->
  </div>
  <!-- End #content -->
  <div id="footer" class="clearfix sidebar-page right-sidebar-page">
    <!-- Start #footer  -->
    <p class="pull-left">
      Copyrights &copy; 2015 <a href="javascript:void(0);" class="color-blue strong" target="_blank">Cashmi</a> by The
      Bam Method Limited. All rights reserved.
    </p>

    <p class="pull-right">
      <a href="#" class="mr5">Terms of use</a>
      |
      <a href="#" class="ml5 mr25">Privacy police</a>
    </p>
  </div>
  <!-- End #footer  -->
</div>
<!-- / #wrapper -->
<!-- Back to top -->
<div id="back-to-top"><a href="#">Back to Top</a>
</div>
<!--[if lt IE 9]>
<script type="text/javascript" src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
</body>

app/views/admins/show.html.erb
<body>
<!--[if lt IE 9]>
<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
<%= render 'admin/navigation' %>
<div id="wrapper">
  <!-- #wrapper -->
  <%= render 'admin/sidebar' %>

  <!--Body content-->
  <div id="content" class="page-content clearfix">
    <div class="contentwrapper">
      <!--Content wrapper-->
      <div class="heading">
        <!--  .heading-->
        <h3>Admin  Dashboard Summary</h3>
        <div class="resBtnSearch">
          <a href="#"><span class="s16 icomoon-icon-search-3"></span></a>
        </div>

        <ul class="breadcrumb">
          <li>You are here:</li>
          <li>
            <a href="#" class="tip" title="back to dashboard">
              <i class="s16 icomoon-icon-screen-2"></i>
            </a>
                                <span class="divider">
                <i class="s16 icomoon-icon-arrow-right-3"></i>
            </span>
          </li>
          <li class="active">Blank Page</li>
        </ul>
      </div>
      <!-- End  / heading-->
      <!-- Start .row -->

      <!-- End .row -->
      <div class="row">
        <div class="col-lg-12">
          <!-- col-lg-12 start here -->
          <div class="panel panel-default toggle panelMove panelClose panelRefresh">
            <!-- Start .panel -->
            <div class="panel-heading">
              <h4 class="panel-title">Admin Applications</h4>

              <div class="table-top-add-tools-btn">
                <a class="btn btn-info mr5" href="<%= admins_new_path %>" ><i class="fa fa-pencil"></i> Add</a>
                <div class="btn-group dropdown mr5">
                  <button data-toggle="dropdown" class="btn btn-info dropdown-toggle" type="button" aria-expanded="false">
                    <i class="fa fa-gears"></i> Tools
                    <span class="caret"></span>
                  </button>
                  <ul role="menu" class="dropdown-menu animated fadeIn" style="margin-left: -49px;">

                    <li>
                      <a href="#"><i class="fa fa-trash-o"></i> Delete</a>
                    </li>


                  </ul>
                </div>
              </div>

            </div>
            <div class="panel-body cstm-table">
              <table id="tabletools" class="table table-striped table-bordered" cellspacing="0" width="100%">
                <thead>
                <tr>
                  <th class="sort-n"><div class="checkbox-custom">
                    <input class="check-all" type="checkbox" id="masterCheck" value="option1">
                    <label for="masterCheck"></label>
                  </div></th>
                  <th>S/N</th>
                  <th>Email</th>
                  <th>Status</th>
                  <th class="last-act">Actions</th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                  <th></th>
                  <th>S/N</th>
                  <th>Email</th>
                  <th>Status</th>
                  <th class="last-act">Actions</th>
                </tr>
                </tfoot>
                <tbody>
                <% @admins.each_with_index do |value, index| %>
                    <tr>
                      <td><div class="checkbox-custom">
                        <input id="check" class="check" type="checkbox" value="option<%= index %>">
                        <label for="check"></label>
                      </div></td>
                      <td><%= index %></td>
                      <td><%= value.email %></td>
                      <td>Active</td>
                      <td>
                        <div class="table-btns">
                          <ul>
                            <li><a href="<%= admins_edit_path value.id %>" class="edt-btn">View / Edit</a></li>
                            <li><a href="<%= admins_delete_path value.id %>" class="view-btn">Delete</a></li>
                          </ul>
                        </div>
                      </td>
                    </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>
          <!-- End .panel -->
        </div>
        <!-- col-lg-12 end here -->
      </div>
      <!-- End .row -->
    </div>
    <!-- End contentwrapper -->
  </div>
  <!-- End #content -->
  <div id="footer" class="clearfix sidebar-page right-sidebar-page">
    <!-- Start #footer  -->
    <p class="pull-left">
      Copyrights &copy; 2015 <a href="javascript:void(0);" class="color-blue strong" target="_blank">Cashmi</a> by The Bam Method Limited. All rights reserved.
    </p>
    <p class="pull-right">
      <a href="#" class="mr5">Terms of use</a>
      |
      <a href="#" class="ml5 mr25">Privacy police</a>
    </p>
  </div>
  <!-- End #footer  -->
</div>
<!-- / #wrapper -->
<!-- Back to top -->
<div id="back-to-top"><a href="#">Back to Top</a>
</div>
</body>