config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  root 'application#index'

  get 'lenders/:id/edit' => 'lenders#edit', as: 'lenders_edit'
  get 'lenders/:id/delete' => 'lenders#delete', as: 'lenders_delete'
  get 'lenders/' => 'lenders#show', as: 'lenders_show'
  get 'lenders_update/' => 'lenders#update', as: 'lenders_update'
  get 'lenders_new/' => 'lenders#new', as: 'lenders_new'
  get 'lenders_save/' => 'lenders#save', as: 'lenders_save'

  get 'borrowers/:id/edit' => 'borrowers#edit', as: 'borrowers_edit'
  get 'borrowers/:id/delete' => 'borrowers#delete', as: 'borrowers_delete'
  get 'borrowers/' => 'borrowers#show', as: 'borrowers_show'
  get 'borrowers_update/' => 'borrowers#update', as: 'borrowers_update'
  get 'borrowers_new/' => 'borrowers#new', as: 'borrowers_new'
  get 'borrowers_save/' => 'borrowers#save', as: 'borrowers_save'

  get 'active_borrowers/' => 'borrowers#active_borrowers', as: 'active_borrowers'
  get 'add_active/' => 'borrowers#add_active', as: 'add_active'
  get 'save_active/' => 'borrowers#save_active', as: 'save_active'
  get 'edit_active/:id/edit' => 'borrowers#edit_active', as: 'borrowers_edit_active'
  get 'save_edit_active/' => 'borrowers#save_edit_active', as: 'save_edit_active'
  get 'confirmed_applications/' => 'borrowers#confirmed_applications', as: 'confirmed_applications'
  get 'add_confirmed/' => 'borrowers#add_confirmed', as: 'add_confirmed'
  get 'save_confirmed/' => 'borrowers#save_confirmed', as: 'save_confirmed'
  get 'edit_confirmed/:id/edit' => 'borrowers#edit_confirmed', as: 'borrowers_edit_confirmed'
  get 'save_edit_confirmed/' => 'borrowers#save_edit_confirmed', as: 'save_edit_confirmed'
  get 'pending_applications/' => 'borrowers#pending_applications', as: 'pending_applications'
  get 'add_pending/' => 'borrowers#add_pending', as: 'add_pending'
  get 'save_pending/' => 'borrowers#save_pending', as: 'save_pending'
  get 'edit_pending/:id/edit' => 'borrowers#edit_pending', as: 'borrowers_edit_pending'
  get 'save_edit_pending/' => 'borrowers#save_edit_pending', as: 'save_edit_pending'

  get 'active_borrowers/:id/delete' => 'borrowers#active_delete', as: 'active_borrowers_delete'

  get 'admins/:id/edit' => 'admins#edit', as: 'admins_edit'
  get 'admins/:id/delete' => 'admins#delete', as: 'admins_delete'
  get 'admins/' => 'admins#show', as: 'admins_show'
  get 'admins_update/' => 'admins#update', as: 'admins_update'
  get 'admins_new/' => 'admins#new', as: 'admins_new'
  get 'admins_save/' => 'admins#save', as: 'admins_save'

  get 'tickets/:id/edit' => 'tickets#edit', as: 'tickets_edit'
  get 'tickets/:id/delete' => 'tickets#delete', as: 'tickets_delete'
  get 'tickets/' => 'tickets#show', as: 'tickets_show'
  get 'tickets_update/' => 'tickets#update', as: 'tickets_update'
  get 'tickets_new/' => 'tickets#new', as: 'tickets_new'

  get 'settings/' => 'settings#show', as: 'settings_show'
  post 'save_terms/' => 'settings#save_terms', as: 'settings_save_terms'
  post 'save_privacy/' => 'settings#save_privacy', as: 'settings_save_privacy'

  get '/ratings', to: 'admins#ratings'
  get '/chats', to: 'admins#chats'

end

app/views/admin/_navigation.html.erb
<div id="header">
  <nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>">
        <%= image_tag 'cashmilogo.png' %>
      </a>
    </div>
    <div id="navbar-no-collapse" class="navbar-no-collapse">
      <ul class="nav navbar-nav">
        <li>
          <!--Sidebar collapse button-->
          <a href="#" class="collapseBtn leftbar"><i class="s16 minia-icon-list-3"></i></a>
        </li>
        <!--<li>
            <a href="#" class="tipB reset-layout" title="Reset panel postions"><i class="s16 icomoon-icon-history"></i></a>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="s16 icomoon-icon-cog-2"></i><span class="txt"> Settings</span>
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu left dropdown-form template-settings">
                <li class="menu">
                    <ul role="menu">
                        <li><strong>Template settings</strong>
                        </li>
                        <li>
                            <div class="toggle-custom">
                                <label class="toggle" data-on="ON" data-off="OFF">
                                    <input type="checkbox" id="fixed-header-toggle" name="fixed-header-toggle" checked>
                                    <span class="button-checkbox"></span>
                                </label>
                                <label for="fixed-header-toggle">Fixed header</label>
                            </div>
                        </li>
                        <li>
                            <div class="toggle-custom">
                                <label class="toggle" data-on="ON" data-off="OFF">
                                    <input type="checkbox" id="fixed-left-sidebar" name="fixed-left-sidebar" checked>
                                    <span class="button-checkbox"></span>
                                </label>
                                <label for="fixed-left-sidebar">Fixed Left Sidebar</label>
                            </div>
                        </li>
                        <li>
                            <div class="toggle-custom">
                                <label class="toggle" data-on="ON" data-off="OFF">
                                    <input type="checkbox" id="fixed-right-sidebar" name="fixed-right-sidebar" checked>
                                    <span class="button-checkbox"></span>
                                </label>
                                <label for="fixed-right-sidebar">Fixed Right Sidebar</label>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </li> -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="s16 minia-icon-envelope"></i><span class="txt">Ticket Messages</span><span class="notification">8</span>
          </a>
          <ul class="dropdown-menu left">
            <li class="menu">
              <ul class="messages">
                <li class="header"><strong>Tickets</strong> (10) Messages</li>
                <li>
                  <span class="icon avatar"><%= image_tag 'avatar.jpg' %></span>
                  <span class="name"><a data-toggle="modal" href="#myModal1"><strong>Sammy
                    Morerira</strong></a><span class="time">35 min ago</span></span>
                  <span class="msg">I have question about new function ...</span>
                </li>
                <li>
                  <span class="icon avatar"><%= image_tag 'avatar.jpg' %></span>
                  <span class="name"><a data-toggle="modal" href="#myModal1"><strong>George
                    Michael</strong></a><span class="time">1 hour ago</span></span>
                  <span class="msg">I need to meet you urgent please call me ...</span>
                </li>
                <li>
                  <span class="icon avatar"><%= image_tag 'avatar.jpg' %></span>
                  <span class="name"><a data-toggle="modal" href="#myModal1"><strong>Ivanovich</strong></a><span class="time">1 day ago</span></span>
                  <span class="msg">I send you my suggestion, please look and ...</span>
                </li>
                <li class="view-all"><a href="#">View all tickets <i class="s16 fa fa-angle-double-right"></i></a>
                </li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-right usernav">
        <!--<li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="s16 icomoon-icon-earth"></i><span class="notification">3</span>
            </a>
            <ul class="dropdown-menu right">
                <li class="menu">
                    <ul class="notif">
                        <li class="header"><strong>Notifications</strong> (3) items</li>
                        <li>
                            <a href="#">
                                <span class="icon"><i class="s16 icomoon-icon-user-plus"></i></span>
                                <span class="event">1 User is registred</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="icon"><i class="s16 icomoon-icon-bubble-3"></i></span>
                                <span class="event">Jony add 1 comment</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="icon"><i class="s16 icomoon-icon-new"></i></span>
                                <span class="event">admin Julia added post with a long description</span>
                            </a>
                        </li>
                        <li class="view-all"><a href="#">View all notifications <i class="s16 fa fa-angle-double-right"></i></a>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>-->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle avatar" data-toggle="dropdown">
            <%= image_tag 'avatar.jpg', class: :image %>
            <span class="txt"><%= current_admin.email %></span>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu right">
            <li class="menu">
              <ul>
                <li><a href="#"><i class="s16 icomoon-icon-user-plus"></i>Edit profile</a>
                </li>
                <!--<li><a href="#"><i class="s16 icomoon-icon-bubble-2"></i>Comments</a>
                </li>-->
                <li><a href="#"><i class="s16 icomoon-icon-plus"></i>Add user</a>
                </li>
              </ul>
            </li>
          </ul>
        </li>
        <li><a href="<%= destroy_admin_session_url %>"><i class="s16 icomoon-icon-exit"></i><span class="txt"> Logout</span></a></li>

      </ul>
    </div>
    <!-- /.nav-collapse -->
  </nav>
  <!-- /navbar -->
</div>
<!-- / #header -->

app/views/admin/_sidebar.html.erb
<!--Sidebar background-->
<div id="sidebarbg" class="hidden-lg hidden-md hidden-sm hidden-xs"></div>
<!--Sidebar content-->
<div id="sidebar" class="page-sidebar hidden-lg hidden-md hidden-sm hidden-xs">
  <!--<div class="shortcuts">
      <ul>
          <li><a href="javascript:void(0);" title="Support section" class="tip"><i class="s24 icomoon-icon-support"></i></a>
          </li>
          <li><a href="#" title="Database backup" class="tip"><i class="s24 icomoon-icon-database"></i></a>
          </li>
          <li><a href="javascript:void(0);" title="Sales statistics" class="tip"><i class="s24 icomoon-icon-pie-2"></i></a>
          </li>
          <li><a href="#" title="Write post" class="tip"><i class="s24 icomoon-icon-pencil"></i></a>
          </li>
      </ul>
  </div>-->
  <!-- End search -->
  <!-- Start .sidebar-inner -->
  <div class="sidebar-inner">
    <!-- Start .sidebar-scrollarea -->
    <div class="sidebar-scrollarea">
      <div class="sidenav">
        <div class="sidebar-widget mb0">
          <h6 class="title mb0">Navigation</h6>
        </div>
        <!-- End .sidenav-widget -->
        <div class="mainnav">
          <ul>
            <li><a href="<%= root_path %>"><i class="s16 icomoon-icon-screen-2"></i><span class="txt">Dashboard</span> </a>
            </li>
            <li>
              <a href="#"><i class="s16 icomoon-icon-user"></i><span class="txt">User management</span> </a>
              <ul class="sub dd-set">
                <li><a href="<%= admins_show_path %>"><i class="s16 icomoon-icon-arrow-right-3"></i><span class="txt">Admin Summary</span></a>
                </li>

                <li><a href="<%= borrowers_show_path %>"><i class="s16 icomoon-icon-arrow-right-3"></i><span class="txt">Borrower Summary</span></a>
                </li>

                <li><a href="<%= lenders_show_path %>"><i class="s16 icomoon-icon-arrow-right-3"></i><span class="txt">lender Summary</span></a>
                </li>

              </ul>
            </li>
            <li>
              <a href="#"><i class="s16 icomoon-icon-coin"></i><span class="txt">Loan management</span> </a>
              <ul class="sub dd-set">
                <li>
                  <a href="<%= active_borrowers_path %>"><i class="s16 icomoon-icon-arrow-right-3"></i><span class="txt">Active Borrower Applications </span></a>
                </li>

                <li>
                  <a href="<%= pending_applications_path %>"><i class="s16 icomoon-icon-arrow-right-3"></i><span class="txt">Pending Borrower Application</span></a>
                </li>

                <li>
                  <a href="<%= confirmed_applications_path %>"><i class="s16 icomoon-icon-arrow-right-3"></i><span class="txt">Confirmed Borrower Applications</span></a>
                </li>

              </ul>
            </li>
            <li>
              <a href="<%= chats_path %>"><i class="s16 icomoon-icon-bubbles-6"></i><span class="txt">Chatting</span></a>
            </li>
            <li>
              <a href="<%= ratings_path %>"><i class="s16 icomoon-icon-star"></i><span class="txt">User Ratings</span></a>
            </li>
            <li>
              <a href="#"><i class="s16 icomoon-icon-database"></i><span class="txt">Lender Database</span> </a>
              <ul class="sub dd-set">
                <li>
                  <a href="lender-db-hong-kong.html"><i class="s16 icomoon-icon-arrow-right-3"></i><span class="txt">Hong Kong </span></a>
                </li>

                <li>
                  <a href="lender-db-singapore.html"><i class="s16 icomoon-icon-arrow-right-3"></i><span class="txt">Singapore</span></a>
                </li>

              </ul>
            </li>
            <li><a href="<%= settings_show_path %>"><i class="s16 icomoon-icon-cog-2"></i><span class="txt">Settings</span></a>
            </li>
            <li>
              <a href="<%= tickets_show_path %>"><i class="s16 icomoon-icon-ticket"></i><span class="txt">Helpdesk Ticket</span></a>
            </li>

          </ul>
        </div>
      </div>
      <!-- End sidenav -->

    </div>
    <!-- End .sidebar-scrollarea -->
  </div>
  <!-- End .sidebar-inner -->
</div>
<!-- End #sidebar -->