config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  root 'application#index'

  get 'lenders/:id/edit' => 'lenders#edit', as: 'lenders_edit'
  get 'lenders/:id/delete' => 'lenders#delete', as: 'lenders_delete'
  get 'lenders/' => 'lenders#show', as: 'lenders_show'
  get 'lenders_update/' => 'lenders#update', as: 'lenders_update'
  get 'lenders_new/' => 'lenders#new', as: 'lenders_new'
  get 'lenders_save/' => 'lenders#save', as: 'lenders_save'

  get 'borrowers/:id/edit' => 'borrowers#edit', as: 'borrowers_edit'
  get 'borrowers/:id/delete' => 'borrowers#delete', as: 'borrowers_delete'
  get 'borrowers/' => 'borrowers#show', as: 'borrowers_show'
  get 'borrowers_update/' => 'borrowers#update', as: 'borrowers_update'
  get 'borrowers_new/' => 'borrowers#new', as: 'borrowers_new'
  get 'borrowers_save/' => 'borrowers#save', as: 'borrowers_save'

  get 'active_borrowers/' => 'borrowers#active_borrowers', as: 'active_borrowers'
  get 'add_active/' => 'borrowers#add_active', as: 'add_active'
  get 'save_active/' => 'borrowers#save_active', as: 'save_active'
  get 'edit_active/:id/edit' => 'borrowers#edit_active', as: 'borrowers_edit_active'
  get 'save_edit_active/' => 'borrowers#save_edit_active', as: 'save_edit_active'
  get 'confirmed_applications/' => 'borrowers#confirmed_applications', as: 'confirmed_applications'
  get 'add_confirmed/' => 'borrowers#add_confirmed', as: 'add_confirmed'
  get 'save_confirmed/' => 'borrowers#save_confirmed', as: 'save_confirmed'
  get 'edit_confirmed/:id/edit' => 'borrowers#edit_confirmed', as: 'borrowers_edit_confirmed'
  get 'save_edit_confirmed/' => 'borrowers#save_edit_confirmed', as: 'save_edit_confirmed'
  get 'pending_applications/' => 'borrowers#pending_applications', as: 'pending_applications'
  get 'add_pending/' => 'borrowers#add_pending', as: 'add_pending'
  get 'save_pending/' => 'borrowers#save_pending', as: 'save_pending'
  get 'edit_pending/:id/edit' => 'borrowers#edit_pending', as: 'borrowers_edit_pending'
  get 'save_edit_pending/' => 'borrowers#save_edit_pending', as: 'save_edit_pending'

  get 'active_borrowers/:id/delete' => 'borrowers#active_delete', as: 'active_borrowers_delete'

  get 'admins/:id/edit' => 'admins#edit', as: 'admins_edit'
  get 'admins/:id/delete' => 'admins#delete', as: 'admins_delete'
  get 'admins/' => 'admins#show', as: 'admins_show'
  get 'admins_update/' => 'admins#update', as: 'admins_update'
  get 'admins_new/' => 'admins#new', as: 'admins_new'
  get 'admins_save/' => 'admins#save', as: 'admins_save'

  get 'tickets/:id/edit' => 'tickets#edit', as: 'tickets_edit'
  get 'tickets/:id/delete' => 'tickets#delete', as: 'tickets_delete'
  get 'tickets/' => 'tickets#show', as: 'tickets_show'
  get 'tickets_update/' => 'tickets#update', as: 'tickets_update'
  get 'tickets_new/' => 'tickets#new', as: 'tickets_new'

  get 'settings/' => 'settings#show', as: 'settings_show'
  post 'save_terms/' => 'settings#save_terms', as: 'settings_save_terms'
  post 'save_privacy/' => 'settings#save_privacy', as: 'settings_save_privacy'

  get '/ratings', to: 'admins#ratings'
  get '/chats', to: 'admins#chats'

end

app/controllers/lenders_controller.rb
class LendersController < ApplicationController

  def show
    @lenders = User.get_lenders
  end

  def edit
    @lender = User.find(params[:id])
  end

  def update
    User.find(params[:user][:id]).update_attributes(update_lender_params params)

    redirect_to lenders_show_url
  end

  def new
    @lender = User.new
  end

  def delete
    User.destroy(params[:id])

    redirect_to lenders_show_url
  end

  def save
    User.create(new_lender_params params)

    redirect_to lenders_show_url
  end

  private

  def update_lender_params(params)
    params.require(:user).permit(:name, :email, :phone, :is_home_rented, :device_type,
                                 :biz_reg_no, :address,
                                 :password, :day_from, :time_from, :zip, :lic_no, :status)
  end

  def new_lender_params(params)
    params.require(:user).permit(:name, :email, :phone, :device_type, :is_home_rented, :lic_no,
                                 :biz_reg_no, :address,
                                 :day_from, :time_from, :country, :zip, :status)
  end

end

app/views/lenders/new.html.erb
<body>
<!--[if lt IE 9]>
<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade
    your browser</a> to improve your experience.</p>
<![endif]-->
<%= render 'admin/navigation' %>
<div id="wrapper">
  <!-- #wrapper -->
  <%= render 'admin/sidebar' %>

  <!--Body content-->
  <div id="content" class="page-content clearfix">
    <div class="contentwrapper">
      <!--Content wrapper-->
      <div class="heading">
        <!--  .heading-->
        <h3>Add New Lender Form</h3>

        <div class="resBtnSearch">
          <a href="#"><span class="s16 icomoon-icon-search-3"></span></a>
        </div>

        <ul class="breadcrumb">
          <li>You are here:</li>
          <li>
            <a href="#" class="tip" title="back to dashboard">
              <i class="s16 icomoon-icon-screen-2"></i>
            </a>
                                <span class="divider">
									<i class="s16 icomoon-icon-arrow-right-3"></i>
								</span>
          </li>
          <li class="active">Blank Page</li>
        </ul>
      </div>
      <!-- End  / heading-->
      <!-- Start .row -->
      <div class="row">
        <div class="col-md-12 sortable-layout">
          <!-- col-md-6 start here -->
          <div class="panel panel-default toggle panelClose panelRefresh panelMove">
            <!-- Start .panel -->
            <div class="panel-heading">
              <h4 class="panel-title"><i class="s16 fa fa-edit"></i> Form</h4>
            </div>
            <div class="panel-body">
              <form class="form-horizontal group-border stripped" action="<%= lenders_save_path %>" role="form">
                <!--<div class="form-group">-->
                  <!--<label class="col-lg-3 control-label" for="">ID Number</label>-->

                  <!--<div class="col-lg-9">-->
                    <!--<input type="text" class="form-control" id="idno" name="IDNumber">-->
                  <!--</div>-->
                <!--</div>-->
                <!-- End .form-group  -->
                <div class="form-group">
                  <label class="col-lg-3 control-label" for="">Name</label>

                  <div class="col-lg-9">
                    <input type="text" class="form-control" id="lastname" name="user[name]">
                  </div>
                </div>
                <!-- End .form-group  -->
                <div class="form-group">
                  <label class="col-lg-3 control-label" for="">Phone</label>

                  <div class="col-lg-9">
                    <input type="text" class="form-control" id="phone" name="user[phone]">
                  </div>
                </div>
                <!-- End .form-group  -->
                <div class="form-group">
                  <label class="col-lg-3 control-label" for="">Email</label>

                  <div class="col-lg-9">
                    <input type="text" class="form-control" id="Email" name="user[email]">
                  </div>
                </div>
                <!-- End .form-group  -->
                <div class="form-group">
                  <label class="col-lg-3 control-label" for="">Device</label>

                  <div class="col-lg-9">
                    <input type="text" class="form-control" id="device" name="user[device_type]">
                  </div>
                </div>
                <!-- End .form-group  -->
                <div class="form-group">
                  <label class="col-lg-3 control-label" for="">License Number</label>

                  <div class="col-lg-9">
                    <input type="text" class="form-control" id="License" name="user[lic_no]">
                  </div>
                </div>
                <!-- End .form-group  -->
                <div class="form-group">
                  <label class="col-lg-3 control-label" for="">Biz Reg Number</label>

                  <div class="col-lg-9">
                    <input type="text" class="form-control" id="Biz" name="user[biz_reg_no]">
                  </div>
                </div>
                <!-- End .form-group  -->
                <div class="form-group">
                  <label class="col-lg-3 control-label" for="">Opening Day</label>

                  <div class="col-lg-9">
                    <input type="text" class="form-control" id="day" name="user[day_from]">
                  </div>
                </div>
                <!-- End .form-group  -->
                <div class="form-group">
                  <label class="col-lg-3 control-label" for="">Opening Time</label>

                  <div class="col-lg-9">
                    <input type="text" class="form-control" id="time" name="user[time_from]">
                  </div>
                </div>
                <!-- End .form-group  -->

                <div class="form-group">
                  <label class="col-lg-3 control-label" for="">Adress</label>

                  <div class="col-lg-9">
                    <input type="text" class="form-control" id="address" name="user[address]">
                  </div>
                </div>
                <!-- End .form-group  -->
                <div class="form-group">
                  <label class="col-lg-3 control-label" for="">Post Code</label>

                  <div class="col-lg-9">
                    <input type="text" class="form-control" id="Post Code" name="user[zip]">
                  </div>
                </div>
                <!-- End .form-group  -->

                <div class="form-group">
                  <label class="col-lg-3 control-label" for="">country</label>

                  <div class="col-lg-9">
                    <select class="fancy-select form-control" name="user[country]">
                      <option value="0">-Select-</option>
                      <option value="1">Singapore</option>
                      <option value="2">option 2</option>
                    </select>
                  </div>
                </div>
                <!-- End .form-group  -->

                <div class="form-group">
                  <label class="col-lg-3 control-label" for="">Status</label>

                  <div class="col-lg-9">
                    <div class="toggle-custom wd-set">
                      <label data-off="Inactive" data-on="Active" class="toggle">
                        <input type="checkbox" checked="" name="user[status]" id="checkbox-toggle">
                        <span class="button-checkbox"></span>
                      </label>
                      <!--<label for="checkbox-toggle">Checked</label>-->
                    </div>
                  </div>
                </div>
                <!-- End .form-group  -->
                <input type="text" name="user[is_staff]" value="1" hidden>


                <div class="view-chat-btm-btn mrt-15">
                  <div class="btn-group">
                    <button class="btn btn-danger" type="submit">Submit</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
          <!-- End .panel -->


        </div>
        <!-- col-md-12 end here -->

      </div>
      <!-- End .row -->
    </div>
    <!-- End contentwrapper -->
  </div>
  <!-- End #content -->
  <div id="footer" class="clearfix sidebar-page right-sidebar-page">
    <!-- Start #footer  -->
    <p class="pull-left">
      Copyrights &copy; 2015 <a href="javascript:void(0);" class="color-blue strong" target="_blank">Cashmi</a> by The
      Bam Method Limited. All rights reserved.
    </p>

    <p class="pull-right">
      <a href="#" class="mr5">Terms of use</a>
      |
      <a href="#" class="ml5 mr25">Privacy police</a>
    </p>
  </div>
  <!-- End #footer  -->
</div>
<!-- / #wrapper -->
<!-- Back to top -->
<div id="back-to-top"><a href="#">Back to Top</a>
</div>
<!--[if lt IE 9]>
<script type="text/javascript" src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
</body>

app/views/lenders/show.html.erb
<body>
<!--[if lt IE 9]>
<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
<%= render 'admin/navigation' %>
<div id="wrapper">
  <!-- #wrapper -->
  <%= render 'admin/sidebar' %>

  <!--Body content-->
  <div id="content" class="page-content clearfix">
    <div class="contentwrapper">
      <!--Content wrapper-->
      <div class="heading">
        <!--  .heading-->
        <h3>Lender Dashboard Summary</h3>
        <div class="resBtnSearch">
          <a href="#"><span class="s16 icomoon-icon-search-3"></span></a>
        </div>

        <ul class="breadcrumb">
          <li>You are here:</li>
          <li>
            <a href="#" class="tip" title="back to dashboard">
              <i class="s16 icomoon-icon-screen-2"></i>
            </a>
                                <span class="divider">
                <i class="s16 icomoon-icon-arrow-right-3"></i>
            </span>
          </li>
          <li class="active">Blank Page</li>
        </ul>
      </div>
      <!-- End  / heading-->
      <!-- Start .row -->
      <div class="row">
        <div class="col-lg-6 col-md-12">
          <!-- col-md-12 start here -->
          <div class="panel panel-default chart">
            <div class="panel-heading">
              <h4 class="panel-title">
                <i class="s16 icomoon-icon-bars"></i>
                <span>Map of Lenders</span>
              </h4>
            </div>
            <div class="panel-body">
              <!--<div id="gmap" style="width:100%;height:230px;"></div>
              <div id="map-canvas" style="width:100%;height:230px;"></div>-->
              <div id="map_wrapper" style="width:100%; height:230px;">
                <div id="map_canvas" class="mapping" style="width:100%; height:100%;"></div>
              </div>
            </div>

          </div>
          <!-- End .panel -->

        </div>
        <!-- col-md-12 end here -->
        <div class="col-lg-6 col-md-12">
          <!-- col-lg-6 start here -->
          <div class="panel panel-default chart">
            <div class="panel-heading">
              <h4 class="panel-title">
                <i class="s16 icomoon-icon-bars"></i>
                <span>Lender Acquisition</span>
              </h4>
            </div>
            <div class="panel-body">
              <div class="auto-update-chart" style="height: 230px;width:100%;">
              </div>
            </div>
          </div>
          <!-- End .panel -->
        </div>
        <!-- col-lg-6 end here -->
      </div>

      <!-- End .row -->






      <div class="row">
        <div class="col-lg-12">
          <!-- col-lg-12 start here -->
          <div class="panel panel-default toggle panelMove panelClose panelRefresh">
            <!-- Start .panel -->
            <div class="panel-heading">
              <h4 class="panel-title">Lender Summary</h4>

              <div class="table-top-add-tools-btn">
                <a class="btn btn-info mr5" href="<%= lenders_new_path %>"><i class="fa fa-pencil"></i> Add</a>
                <div class="btn-group dropdown mr5">
                  <button data-toggle="dropdown" class="btn btn-info dropdown-toggle" type="button" aria-expanded="false">
                    <i class="fa fa-gears"></i> Tools
                    <span class="caret"></span>
                  </button>
                  <ul role="menu" class="dropdown-menu animated fadeIn" style="margin-left: -49px;">

                    <li>
                      <a href="#"><i class="fa fa-trash-o"></i> Delete</a>
                    </li>


                  </ul>
                </div>
              </div>

            </div>
            <div class="panel-body cstm-table valign">
              <table id="tabletools" class="table table-striped table-bordered" cellspacing="0" width="100%">
                <thead>
                <tr>
                  <th class="sort-n"><div class="checkbox-custom">
                    <input class="check-all" type="checkbox" id="masterCheck" value="option1">
                    <label for="masterCheck"></label>
                  </div></th>
                  <th>S/N</th>
                  <th>ID</th>
                  <th>Name</th>
                  <th>Phone</th>
                  <th>Email</th>
                  <th>Device</th>
                  <th>License Number</th>
                  <th>Biz Reg Number</th>
                  <th>Opening Day Time</th>
                  <th>Address</th>
                  <th>post code</th>
                  <th>country</th>
                  <th>Status</th>
                  <th class="last-act">Actions</th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                  <th></th>
                  <th>S/N</th>
                  <th>ID</th>
                  <th>Name</th>
                  <th>Phone</th>
                  <th>Email</th>
                  <th>Device</th>
                  <th>License Number</th>
                  <th>Biz Reg Number</th>
                  <th>Opening Day Time</th>
                  <th>Address</th>
                  <th>post code</th>
                  <th>country</th>
                  <th>Status</th>
                  <th class="last-act">Actions</th>
                </tr>
                </tfoot>
                <tbody>
                <% @lenders.each_with_index do |value, index| %>
                    <tr>
                      <td><div class="checkbox-custom">
                        <input id="check" class="check" type="checkbox" value="option<%= index %>">
                        <label for="check"></label>
                      </div></td>
                      <td><%= index %></td>
                      <td><%= value.id %></td>
                      <td><%= value.name %></td>
                      <td><%= value.phone %></td>
                      <td><%= value.email %></td>
                      <td><%= value.device_type %></td>
                      <td><%= value.lic_no %></td>
                      <td><%= value.biz_reg_no %></td>
                      <td><span class="day"><%= value.day_from %></span> <%= value.time_from %></td>
                      <td><%= value.address %></td>
                      <td><%= value.zip %></td>
                      <td><%= value.country %></td>
                      <td><%= value.status %></td>
                      <td>
                        <div class="table-btns">
                          <ul>
                            <li><a href="<%= lenders_edit_path value.id %>" class="edt-btn">View/Edit</a></li>
                            <li><a href="<%= lenders_delete_path value.id %>" class="view-btn">Delete</a></li>
                          </ul>
                        </div>
                      </td>
                    </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>
          <!-- End .panel -->
        </div>
        <!-- col-lg-12 end here -->
      </div>
      <!-- End .row -->
    </div>
    <!-- End contentwrapper -->
  </div>
  <!-- End #content -->
  <div id="footer" class="clearfix sidebar-page">
    <!-- Start #footer  -->
    <p class="pull-left">
      Copyrights &copy; 2015 <a href="javascript:void(0);" class="color-blue strong" target="_blank">Cashmi</a> by The Bam Method Limited. All rights reserved.
    </p>
    <p class="pull-right">
      <a href="#" class="mr5">Terms of use</a>
      |
      <a href="#" class="ml5 mr25">Privacy police</a>
    </p>
  </div>
  <!-- End #footer  -->
</div>
<!-- / #wrapper -->
<!-- Back to top -->
<div id="back-to-top"><a href="#">Back to Top</a>
</div>

<!--<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true"></script>
<script>
function initialize() {
var myLatlng = new google.maps.LatLng(1.27996579, 103.85057896);
var myLatlng = new google.maps.LatLng(1.2872702, 103.84589914);
var mapOptions = {
zoom: 14,
center: myLatlng
}
var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

var marker = new google.maps.Marker({
position: myLatlng,
map: map,
title: 'Hello World!'
});
infowindow = new google.maps.InfoWindow({content:"<b>license number</b><br/>Singapore" });
google.maps.event.addListener(marker, "click", function(){infowindow.open(map,marker);});


}

google.maps.event.addDomListener(window, 'load', initialize);

</script>-->

<script>
    jQuery(function($) {
        // Asynchronously Load the map API
        var script = document.createElement('script');
        script.src = "http://maps.googleapis.com/maps/api/js?sensor=false&callback=initialize";
        document.body.appendChild(script);
    });

    function initialize() {
        var map;
        var bounds = new google.maps.LatLngBounds();
        var mapOptions = {
            mapTypeId: 'roadmap'
        };

        // Display a map on the page
        map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
        map.setTilt(45);

        // Multiple Markers
        var markers = [
            ['Singapore', 1.27996579, 103.85057896],
            ['Singapore', 1.28559693, 103.84452585],
            ['New Bridge, Singapore', 1.27985442, 103.83962989]
        ];

        // Info Window Content
        var infoWindowContent = [
            ['<div class="info_content">' +
            '<h3>000-000-000</h3>' +
            '<p>Lorem Ipsum is simply<br> dummy text </p>' +        '</div>'],
            ['<div class="info_content">' +
            '<h3>000-000-000</h3>' +
            '<p>Lorem Ipsum is simply<br> dummy text </p>' +        '</div>'],
            ['<div class="info_content">' +
            '<h3>000-000-000</h3>' +
            '<p>Lorem Ipsum is simply<br> dummy text </p>' +
            '</div>']
        ];

        // Display multiple markers on a map
        var infoWindow = new google.maps.InfoWindow(), marker, i;

        // Loop through our array of markers & place each one on the map
        for( i = 0; i < markers.length; i++ ) {
            var position = new google.maps.LatLng(markers[i][1], markers[i][2]);
            bounds.extend(position);
            marker = new google.maps.Marker({
                position: position,
                map: map,
                title: markers[i][0]
            });

            // Allow each marker to have an info window
            google.maps.event.addListener(marker, 'click', (function(marker, i) {
                return function() {
                    infoWindow.setContent(infoWindowContent[i][0]);
                    infoWindow.open(map, marker);
                }
            })(marker, i));

            // Automatically center the map fitting all markers on the screen
            map.fitBounds(bounds);
        }

        // Override our map zoom level once our fitBounds function runs (Make sure it only runs once)
        var boundsListener = google.maps.event.addListener((map), 'bounds_changed', function(event) {
            this.setZoom(14);
            google.maps.event.removeListener(boundsListener);
        });

    }

</script>

</body>